points:
  zones:
    rights:
      columns:
        outer2:
        outer1:
      rows:
        ctrl.asym: clone
        bottom.asym: clone
        home.asym: clone
        top.asym: clone
        num.asym: clone
        fn:
          asym: clone
          shift: [0, 5]
    outer:
      anchor:
        ref: rights_outer1_ctrl
        shift: [19, 0]
      columns:
        outer:
      rows:
        ctrl:
        bottom:
        home:
        top:
        num:
        fn:
          shift: [0, 5]
    matrix:
      anchor:
        ref: outer_outer_bottom
        shift: [19, 0]
      columns:
        pinky:
        ring.key.stagger: 6
        middle.key.stagger: 5
        index.key.stagger: -5
        inner.key.stagger: 0
      rows:
        bottom:
        home:
        top:
        num:
        fn:
          shift: [0, 5]
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-19, -21]
      columns:
        nearest:
        near:
        home.key:
          spread: 19
          splay: -35
          #shift: [3, -6]
          origin: [-11.75, -9]
        far.key:
          spread: 19
          splay: -35
          #shift: [7, -11]
          origin: [-9.5, -9]
      rows:
        thumb:
    #lowthumb:
    #  anchor:
    #    ref: thumbfan_nearest_thumb
    #    shift: [0, -19]
    #  columns:
    #    lo1:
    #    lo2:
    #  rows:
    #    thumb:
  mirror:
    ref: matrix_index_num
    distance: 160
outlines:
  outline:
    main:
      what: rectangle
      where: true
      size: 33
      bevel: 3
    min:
      what: rectangle
      where: true
      bound: false
      size: 14
      operation: subtract
cases:
  board4:
    - name: outline
      extrude: 1.5
